import { StyleSheet, Dimensions, Platform } from "react-native";
import { DefaultTheme } from "react-native-paper";
import { getStatusBarHeight } from "react-native-status-bar-height";

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    text: "#FFFFFF",
    primary: "#4E53BA",
    secondary: "#110580",
    tertiary: "#E8E8F7",
    subtext: "#868AE0",
    error: "#f13a59",
  },
};

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  welcomebg: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    width: windowWidth,
  },
  // WELCOME PAGE
  welcomecontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    width: "100%",
    maxWidth: 340,
    marginTop: (Platform.OS === 'ios') ? "110%" : "87%",
  },
  welcomeheader: {
    fontSize: 32,
    color: theme.colors.text,
    fontFamily: "roboto-bold",
    paddingVertical: 12,
  },
  welcometext: {
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.text,
    textAlign: "center",
    fontFamily: "roboto-light",
    marginBottom: (Platform.OS === 'ios') ? "50%" : "20%",
  },
  // MAIN BUTTON
  button: {
    width: 160,
    paddingVertical: 3,
    borderRadius: 50,
    backgroundColor: theme.colors.primary,
  },
  buttonYes: {
    width: 160,
    paddingVertical: 3,
    borderRadius: 50,
    backgroundColor: theme.colors.primary,
    margin: 10,
  },
  buttonunselected: {
    width: 160,
    paddingVertical: 3,
    borderRadius: 50,
    backgroundColor: theme.colors.tertiary,
    margin: 10,
  },
  buttonNot: {
    width: 160,
    paddingVertical: 3,
    borderRadius: 50,
    backgroundColor: theme.colors.tertiary,
    margin: 10,
  },
  buttontext: {
    fontFamily: "roboto-regular",
    fontSize: 16,
    lineHeight: 16,
    color: theme.colors.text,
  },
  // ONBOARD PAGE
  onboardcontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    width: windowWidth,
    paddingBottom: "15%",
    height: windowHeight,
    backgroundColor: theme.colors.text,
  },
  onboard1: {
    flex: 1,
    width: "80%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "30%",
  },
  openingheader: {
    fontSize: 32,
    backgroundColor: (Platform.OS === 'ios') ? null : "rgba(255, 255, 255, 0.75)",
    color: theme.colors.secondary,
    fontFamily: "roboto-bold",
    paddingBottom: (Platform.OS === 'ios') ? "2%" : "4%",
    paddingTop: (Platform.OS === 'ios') ? "2%" : "7%",
    paddingHorizontal: (Platform.OS === 'ios') ? 0 : "15%",
  },
  openingtext: {
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.subtext,
    textAlign: "center",
    fontFamily: "roboto-light",
    marginBottom: "20%",
    paddingHorizontal: 45,
  },
  onboard2: {
    flex: 1,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "30%",
  },
  onboard3: {
    flex: 1,
    width: "80%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "30%",
  },
  roundcontainer: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: "20%",
  },
  darkround: {
    backgroundColor: theme.colors.primary,
    width: 8,
    height: 8,
    borderRadius: 50,
    marginRight: 9,
  },
  lightround: {
    backgroundColor: theme.colors.tertiary,
    width: 8,
    height: 8,
    borderRadius: 50,
    marginRight: 9,
  },
  // REGISTER PAGE
  registercontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 0,
    width: windowWidth,
    paddingTop: (Platform.OS === 'ios') ? "5%" : 0,
    paddingBottom: (Platform.OS === 'ios') ? "10%" : "7%",
    height: windowHeight,
    backgroundColor: theme.colors.text,
  },
  register: { // IMAGE
    flex: 1,
    resizeMode: "contain",
    width: (Platform.OS === 'ios') ? "55%" : "50%",
    alignItems: "center",
    justifyContent: "center",
  },
  keyboardavoiding: {
    flex: 1,
    marginBottom: (Platform.OS === 'ios') ? 5 : "26%",
    marginTop: (Platform.OS === 'ios') ? 0 : "3.5%",
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  reginputcontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: windowWidth,
    paddingBottom: (Platform.OS === 'ios') ? "15%" : "1%",
    height: windowHeight,
  },
  registerrow: {
    flexDirection: "row",
    paddingTop: (Platform.OS === 'ios') ? "5%" : "2%",
  },
  registertext: {
    fontFamily: "roboto-regular",
    color: theme.colors.subtext,
  },
  link: {
    fontFamily: "roboto-bold",
    color: theme.colors.primary,
  },
  // LOGIN PAGE
  keyboardavoiding2: {
    flex: 1,
    marginBottom: (Platform.OS === 'ios') ? 5 : "16%",
    marginTop: (Platform.OS === 'ios') ? 0 : "-5%",
    paddingTop: (Platform.OS === 'ios') ? 0 : "-10%",
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  logincontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: windowWidth,
    paddingBottom: (Platform.OS === 'ios') ? "25%" : "5%",
    height: windowHeight,
  },
  login: { // IMAGE
    flex: 1,
    resizeMode: "contain",
    width: (Platform.OS === 'ios') ? "65%" : "50%",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "10%",
  },
  logindescription: {
    fontSize: 13,
    color: theme.colors.secondary,
    paddingTop: 8,
  },
  loginerror: {
    fontSize: 13,
    color: theme.colors.error,
    paddingTop: 8,
  },
  backbtncontainer: {
    position: "absolute",
    top: 10 + getStatusBarHeight(),
    left: 4,
  },
  backbtn: {
    width: 35,
    height: 35,
  },
  editbtn: {
    position: "absolute",
    top: 10 + getStatusBarHeight(),
    right: 4,
  },
  camerabtn: {
    position: "absolute",
    top: 100 + getStatusBarHeight(),
    right: 140,
  },
  profilepic: {
    position: "absolute",
    top: 50 + getStatusBarHeight(),
  },
  profilename: {
    position: "absolute",
    top: 10 + getStatusBarHeight(),
    color: "#110580",
    fontSize: 20,
    paddingBottom: "5%",
    fontFamily: "roboto-bold",
  },
  popheader: {
    // position: "absolute",
    // top: 10 + getStatusBarHeight(),
    color: "#110580",
    fontSize: 20,
    // paddingBottom: "5%",
    fontFamily: "roboto-bold",
    textAlign:"center",
  },
  profileemail: {
    position: "absolute",
    top: 160 + getStatusBarHeight(),
    color: "#110580",
    fontSize: 16,
    fontFamily: "roboto-medium",
  },
  forgotPassword: {
    width: "100%",
    alignItems: "flex-end",
    marginBottom: 24,
  },
  forgot: {
    fontSize: 13,
    color: theme.colors.secondary,
  },
  // Text input component
  textinputcontainer: {
    width: "85%",
    marginTop: 5,
  },
  textinput: {
    backgroundColor: theme.colors.text,
    borderRadius: 50,
    fontSize: 16,
  },
  textinputdescription: {
    fontSize: 13,
    color: theme.colors.secondary,
    paddingTop: 8,
  },
  textinputerror: {
    fontSize: 12,
    color: theme.colors.error,
  },
  // Create Habit
  habitcontainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingVertical: 50,
    width: "100%",
  },
  profilecontainer: {
    // flex: 1,
    backgroundColor: "#E8E8F7",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingVertical: 110,
    // paddingHorizontal: 20,
    width: "100%",
  },
  profilecontainer2: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "flex-start",
    // paddingVertical: 110,
    // paddingHorizontal: 20,
    width: "100%",
    // borderRadius: 100,
  },
  profilecontainer3: {
    flex: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "flex-start",
    // paddingHorizontal: 20,
    width: "100%",
    // borderRadius: 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  topHeader: {
    color: "#110580",
    fontSize: 20,
    paddingBottom: "5%",
    fontFamily: "roboto-bold",
  },
  headerTxt: {
    color: "#110580",
    fontSize: 16,
    alignSelf: "flex-start",
    marginTop: 15,
    paddingLeft: 35,
    fontFamily: "roboto-medium",
  },
  popTxt: {
    color: "#110580",
    fontSize: 16,
    // alignSelf: "flex-start",
    // marginTop: 15,
    // paddingLeft: 35,
    fontFamily: "roboto-medium",
    textAlign:"center",
  },
  freqDropdown: {
    paddingVertical: 20,
    borderWidth: 0.5,
    alignSelf: "center",
    width: "85%",
    borderRadius: 30,
    marginVertical: 15,
    fontSize: 20,
    zIndex: 1,
  },
  freqPlaceholder: {
    fontSize: 16,
    color: theme.colors.primary,
    fontFamily: "roboto-medium",
    paddingHorizontal: 8,
  },
  freqText: {
    fontSize: 16,
    fontFamily: "roboto-medium",
    paddingHorizontal: 8,
    color: theme.colors.primary,
  },
  dayDropdown: {
    fontSize: 16,
    fontFamily: "roboto-medium",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderWidth: 0.5,
    alignSelf: "center",
    width: "85%",
    borderRadius: 50,
    marginBottom: 50,
  },
  dropDown: {
    width: "85%",
    alignSelf: "center",
    fontSize: 10,
    fontFamily: "roboto-medium",
    borderWidth: 0.5,
  },
  listItemDropdown: {
    fontFamily: "roboto-light",
    color: theme.colors.primary,
    fontSize: 16,
  },
  badgeTextDropdown: {
    fontFamily: "roboto-regular",
    fontSize: 14,
    color: theme.colors.text,
  },
});
